use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'AutoData_Example' do
  pod 'AutoData', :path => '../'

  target 'AutoData_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'AutoModel'
    pod 'NFAToolkit'
    pod 'NFASQLiteDB'
    pod 'NFANetwork'
  end
end
